- name: Get eth0 IP for VM {{ item.name }}
  shell: >
   virsh qemu-agent-command {{ item.name }} \
   '{"execute":"guest-network-get-interfaces"}' | \
   sed -n 's/.*"ip-address":"\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/p'
  register: interface0_out
  until: interface0_out.stdout | length > 0
  retries: 3
  delay: 5
  changed_when: false

- name: sleep for 10 seconds to ensure connection not refused
  wait_for: timeout=10
  delegate_to: localhost

- name: Wait for ssh readiness
  command: >
    ssh -o StrictHostKeyChecking=no
    {{ ansible_user_id }}@{{ interface0_out.stdout }} hostname
  delegate_to: localhost
  ignore_errors: true
  register: ssh_out
  until: interface0_out.stdout | length > 0
  retries: 10
  delay: 5
  changed_when: false

- name: Set the host_entry fact
  set_fact:
    host_entry: "{{ ssh_out.stdout }}"

- name: More fact setting for the interface
  set_fact:
    host_entry: "{{ interface0_out.stdout }}"
  when: "'localhost' in ssh_out.stdout"

- name: Ensure ssh is working
  command: >
    ssh -o StrictHostKeyChecking=no {{ ansible_user_id }}@{{ host_entry }}
  delegate_to: localhost
  changed_when: false

- name: Add host to inventory in memory
  add_host:
    name: "{{ host_entry }}"
    groups: "{{ item.type }}"
